export default {
  TEST_ACTION: 'TEST_ACTION',
  UPLOAD_BOOKMARK: 'UPLOAD_BOOKMARK',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
};
